name: libota
description: LibOTA ebook reader
publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  epub_view: ^3.2.0
  shared_preferences: ^2.2.2
  path_provider: ^2.1.2
  cached_network_image: ^3.3.1
  provider: ^6.1.2
  file_picker: ^8.0.0
  url_launcher: ^6.2.6
  webview_flutter: ^4.7.0
  pdfx: ^2.6.0
  flutter_pdfview: ^1.3.2
  xml: ^6.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.11.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/icon/app_icon.png

  adaptive_icon_foreground: assets/icon/app_icon.png
  adaptive_icon_background: "#5B2EFF"

flutter:
  uses-material-design: true
